### ISSUE TITLE
Does not always find the latest

### ISSUE THREAD

**Issue by john-kurkowski** [jkoenig134/gha-check-updates#1]
Hey love this tool! Surprised no one else has done it.

I ran `npx gha-check-updates` out on the following example workflow from [Lost Pixel](https://github.com/lost-pixel/lost-pixel)'s onboarding. I found gcu wasn't always finding the latest tag of a project. 

# Expected

```
  Action 'actions/checkout@v3' has a newer version available: 'v4' or 'v4.1.2'.
  Action 'actions/setup-node@v3' has a newer version available: 'v4' or 'v4.0.2'.
  Action 'lost-pixel/lost-pixel@v3' has a newer version available: 'v3' or 'v3.16.0'.
```

# Actual

```
  Action 'actions/checkout@v3' has a newer version available: 'v4' or 'v4.1.2'.
  Action 'actions/setup-node@v3' has a newer version available: 'v4' or 'v4.0.2'.
  Action 'lost-pixel/lost-pixel@v3' has a newer version available: 'undefined' or 'v3.9.0'.
```

# Workflow example provided by Lost Pixel's onboarding

```yml
// .github/workflows/vrt.yml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lost Pixel

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Start server (in background)
        run: npm run start &

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.4.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
```
