### ISSUE TITLE
Checked "newer version available" suggestions are not correct

### ISSUE THREAD

**Issue by mwtoews** [jkoenig134/gha-check-updates#4]
I have a `release.yml` file that has some content [documented here](https://github.com/pypa/gh-action-pypi-publish):
```yml
jobs:
  release:
    steps:
     # ...
      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```
When running `gha-check-updates` in a `node:23-bookworm` docker container, I first get an error:
```
Checked /path/to/.github/workflows/release.yml ✗
  Action 'pypa/gh-action-pypi-publish@release/v1' has a newer version available: 'v1.12.4'.
```
Isn't `v1` equivalent to `v1.12.4`? Ok, lets take that suggestion and re-run the check:
```
Checked /path-to/.github/workflows/release.yml ✗
  Action 'pypa/gh-action-pypi-publish@release/v1.12.4' has a newer version available: 'v1.12.4'.
```
The suggested "newer" version is the same as the version specified in the action. What's going on here?
